INSERT INTO `nationality` (`title`) VALUES
('Afghan'),
('Albanian'),
('Algerian'),
('Andorran'),
('Angolan'),
('Antiguans, Barbudans'),
('Argentinean'),
('Armenian'),
('Australian'),
('Austrian'),
('Azerbaijani'),
('Bahamian'),
('Bahraini'),
('Bangladeshi'),
('Barbadian'),
('Belarusian'),
('Belgian'),
('Belizean'),
('Beninese'),
('Bhutanese'),
('Bolivian'),
('Bosnian, Herzegovinian'),
('Motswana (singular), Batswana (plural)'),
('Brazilian'),
('Bruneian'),
('Bulgarian'),
('Burkinabe'),
('Burundian'),
('Cambodian'),
('Cameroonian'),
('Canadian'),
('Cape Verdian'),
('Central African'),
('Chadian'),
('Chilean'),
('Chinese'),
('Colombian'),
('Comoran'),
('Congolese'),
('Costa Rican'),
('Ivorian'),
('Croatian'),
('Cuban'),
('Cypriot'),
('Czech'),
('Danish'),
('Djibouti'),
('Dominican'),
('East Timorese'),
('Ecuadorean'),
('Egyptian'),
('Salvadoran'),
('Equatorial Guinean'),
('Eritrean'),
('Estonian'),
('Ethiopian'),
('Fijian'),
('Finnish'),
('French'),
('Gabonese'),
('Gambian'),
('Georgian'),
('German'),
('Ghanaian'),
('Greek'),
('Grenadian'),
('Guatemalan'),
('Guinean'),
('Guinea-Bissauan'),
('Guyanese'),
('Haitian'),
('Honduran'),
('Hungarian'),
('Icelander'),
('Indian'),
('Indonesian'),
('Iranian'),
('Iraqi'),
('Irish'),
('Israeli'),
('Italian'),
('Jamaican'),
('Japanese'),
('Jordanian'),
('Kazakhstani'),
('Kenyan'),
('I-Kiribati'),
('North Korean'),
('South Korean'),
('Kuwaiti'),
('Kirghiz'),
('Laotian'),
('Latvian'),
('Lebanese'),
('Mosotho'),
('Liberian'),
('Libyan'),
('Liechtensteiner'),
('Lithuanian'),
('Luxembourger'),
('Macedonian'),
('Malagasy'),
('Malawian'),
('Malaysian'),
('Maldivan'),
('Malian'),
('Maltese'),
('Marshallese'),
('Mauritanian'),
('Mauritian'),
('Mexican'),
('Micronesian'),
('Moldovan'),
('Monegasque'),
('Mongolian'),
('Moroccan'),
('Mozambican'),
('Burmese'),
('Namibian'),
('Nauruan'),
('Nepalese'),
('Dutch'),
('New Zealander'),
('Nicaraguan'),
('Nigerien'),
('Nigerian'),
('Norwegian'),
('Omani'),
('Pakistani'),
('Palauan'),
('Panamanian'),
('Papua New Guinean'),
('Paraguayan'),
('Peruvian'),
('Filipino'),
('Polish'),
('Portuguese'),
('Qatari'),
('Romanian'),
('Russian'),
('Rwandan'),
('Kittian and Nevisian'),
('Saint Lucian'),
('Samoan'),
('Sammarinese'),
('Sao Tomean'),
('Saudi Arabian'),
('Senegalese'),
('Serbian'),
('Seychellois'),
('Sierra Leonean'),
('Singaporean'),
('Slovak'),
('Slovene'),
('Solomon Islander'),
('Somali'),
('South African'),
('Spanish'),
('Sri Lankan'),
('Sudanese'),
('Surinamer'),
('Swazi'),
('Swedish'),
('Swiss'),
('Syrian'),
('Taiwanese'),
('Tadzhik'),
('Tanzanian'),
('Thai'),
('Togolese'),
('Tongan'),
('Trinidadian'),
('Tunisian'),
('Turkish'),
('Turkmen'),
('Tuvaluan'),
('Ugandan'),
('Ukrainian'),
('Emirian'),
('British'),
('American'),
('Uruguayan'),
('Uzbekistani'),
('Ni-Vanuatu'),
('none'),
('Venezuelan'),
('Vietnamese'),
('Yemeni'),
('Zambian'),
('Zimbabwean');
